DROP TABLE EVENTS IF EXISTS;

CREATE TABLE EVENTS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT EVENT_NAME_UNIQUE UNIQUE (NAME)
);

CREATE INDEX EVENT_NAME_INDEX ON EVENTS(NAME);

INSERT INTO EVENTS (ID, NAME) VALUES (1, 'England championship');
INSERT INTO EVENTS (ID, NAME) VALUES (2, 'England prime league');