drop table EVENTS IF EXISTS;

CREATE TABLE EVENTS
(
    EVENT_ID INT,
    NAME VARCHAR(255)
);

INSERT INTO EVENTS (EVENT_ID, NAME) VALUES (1, 'England championship');
INSERT INTO EVENTS (EVENT_ID, NAME) VALUES (2, 'England prime league');