DROP TABLE PARSERS IF EXISTS;

CREATE TABLE PARSERS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

INSERT INTO PARSERS (ID, NAME) VALUES (1, 'WideTableTeamTableTeamParser');
INSERT INTO PARSERS (ID, NAME) VALUES (2, 'FormTableTeamTableTeamParser');
INSERT INTO PARSERS (ID, NAME) VALUES (3, 'OverUnderTableTeamParser');