DROP TABLE TASKS IF EXISTS;

CREATE TABLE TASKS
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SESSION_ID INT NOT NULL,
    ROUND_ID INT NOT NULL,
    COMPETITION_ID INT NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    PARSER_ID INT NOT NULL,
    EVENT_ID INT NOT NULL
);

CREATE INDEX PARSER_ID_INDEX ON PARSERS(ID);
CREATE INDEX EVENT_ID_INDEX ON EVENTS(ID);

ALTER TABLE TASKS ADD FOREIGN KEY(PARSER_ID) REFERENCES PARSERS(ID);
ALTER TABLE TASKS ADD FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(ID);

INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (1, 14218, 42070, 70, 'competition_wide_table', 1, 1);
INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (2, 14218, 42070, 70, 'competition_form_table', 2, 1);
INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (3, 14218, 42070, 70, 'competition_overunder_table', 3, 1);

INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (4, 14029, 41547, 8, 'competition_wide_table', 1, 2);
INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (5, 14029, 41547, 8, 'competition_form_table', 2, 2);
INSERT INTO TASKS (ID, SESSION_ID, ROUND_ID, COMPETITION_ID, TYPE, PARSER_ID, EVENT_ID)
VALUES (6, 14029, 41547, 8, 'competition_overunder_table', 3, 2);